### ISSUE TITLE
Unable to load dynamic library

### ISSUE THREAD

**Issue by ntthung** [eddelbuettel/rcppziggurat#15]
Hi Dirk,

I am using the package Rfast, which imports RcppZiggurat. I got the following error when running Rfast on a Linux cluster (Red Hat 6.10)

```
unable to load shared object '/home/users/sutd/R/x86_64-pc-linux-gnu-library/3.6/RcppZiggurat/libs/RcppZiggurat.so':
  libgsl.so.0: cannot open shared object file: No such file or directory
```

The packages are installed on my local directory. Edited: I've done some diagnostic and found that this only happens when the Rfast functions are being called in parallel, in a `foreach()` loop. When they are called directly it is OK.

Below are something I've tried but failed:

I know that libgsl.so is located in /usr/lib64/, so I've added the following line at the beginning of my R script

```
Sys.setenv(LD_LIBRARY_PATH=paste("/usr/lib64/", Sys.getenv("LD_LIBRARY_PATH"), sep = ":"))
```

I have also try to do `dyn.load('/usr/lib64/libgsl.so')` but I get the following error

```
 Error in dyn.load("/usr/lib64/libgsl.so") :
  unable to load shared object '/usr/lib64/libgsl.so':
  /usr/lib64/libgsl.so: undefined symbol: cblas_ctrmv
```

On Windows everything works fine.

Is this an issue or am I doing something wrong?

Thank you so much.

**Comment by eddelbuettel** [comment]
I fear that is between you and your RHEL machine as CRAN is happy (and has generally been):  

![image](https://user-images.githubusercontent.com/673121/97298404-5e4ca200-1821-11eb-9e81-60cba4e88ee1.png)

**Comment by eddelbuettel** [comment]
And [Crossposted to StackOverflow](https://stackoverflow.com/questions/64551253/dynamic-library-dependencies-not-recognized-when-run-in-parallel-under-r-foreach) which seems to [indicate you did not set up your parallel code right](https://stackoverflow.com/a/64552534/143305). I think Rui is correct and you need to register the cluster.
