### ISSUE TITLE
Use .Random.seed

### ISSUE THREAD

**Issue by twolodzko** [eddelbuettel/rcppziggurat#5]
I have a question/feature request: is there any reason why RcppZiggurat does not use R's seeding mechanism? Consistent control of seeds seems to be important from reproducibility point of view. If there is any problem with using the R's seeds, I'd be interested in learning about it and potentially helping with solving it (if it is already described in the docs I must have missed it).

**Comment by eddelbuettel** [comment]
It is not using R's own generators making R's seeding a little out of place. [ Do study that code by the way, it is very complicated.  We give R one seed, but eg the Mersenne Twister generator (for uniforms) has hundreds of state variables. ]

So this is its own generator with its own seed.

**Comment by twolodzko** [comment]
@eddelbuettel I did go through the code. I understand that different formats of seeds are used, but you can always expand a seed using some PRG. This would harm performance, but since it is much more efficient then `rnorm`, maybe it is still worth it.
